name: crypto-recovery-tool
services:
  - name: api
    git:
      repository: github.com/Soeg1916/mine
      branch: main
    build:
      builder: nodejs
      nodejs:
        version: "20"
        build_command: npm install && npm run build
        run_command: npm start
    ports:
      - port: 5000
        http: public
    env:
      - key: NODE_ENV
        value: production
    regions:
      - fra
    instance_type: nano
    scaling:
      min: 1
      max: 1